name: fast_app
description: A new Flutter package project.
version: 1.0.1
homepage: https://github.com/qiuguian/fast_app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
  intl: ^0.17.0
  scoped_model: ^2.0.0-nullsafety.0
  shared_preferences: ^2.0.5
  dio_http2_adapter: ^2.0.0
  html: ^0.15.0
  flutter_swiper_null_safety:  ^1.0.1
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
#  fluwx: any
  json_annotation: ^4.1.0
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.3
  flutter_easyloading: ^3.0.0
  photo_view: ^0.13.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/ic_common_empty.png
    - assets/loading.gif
    - assets/ic_confirm.webp