name: fast_app
description: A new Flutter package project.
version: 0.0.3
author: qiuguian <fastappchina@gmail.com>
homepage: https://github.com/qiuguian/fast_app

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.7
  grpc: ^2.1.2
  protobuf: ^1.0.0
  intl: ^0.16.0
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.4+8
  dio_http2_adapter: ^1.0.0
  html: ^0.14.0+3
  flutter_swiper:  ^1.1.6
  cached_network_image: 2.2.0+1
  cupertino_icons: ^0.1.2
#  fluwx: any
  json_annotation: ^3.1.0
  toast:  ^0.1.5
  url_launcher: ^5.4.2
  flutter_easyloading: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/ic_common_empty.png
    - assets/loading.gif
    - assets/ic_confirm.webp